### PR TITLE
Add command: export to HTML

### PR DESCRIPTION
**Pull request by myguidingstar-zz**

### CODE REVIEW

**Comment by MarcoPolo** [comment]
Looks good! Thanks!

**Comment by myguidingstar-zz** [comment]
I'm considering using pandoc[1](http://johnmacfarlane.net/pandoc/demo/example9/pandocs-markdown.html) instead of marked, or at least make it an option, because of its feature fullness  - even exporting to PDF, Office formats is possible.

What do you think?

**Comment by MarcoPolo** [comment]
That sounds nice! Test it with big(ish) marked down files and see if it renders just as quickly. 

Marked renders the markdown after every change, and it's really fast so you don't notice any delay.

That and it should look somewhat like github's markdown mainly because I see that as a big use case for devs who want to see what their markdown will look like on github.

If you got the time, go for it! :thumbsup:  I'll probably not be able to help out a whole lot though :frowning: 

It might even be better to create a separate pandoc command/plugin that will use pandoc to make the output formats.

**Comment by bilderbuchi** [comment]
pandoc supports github flavored markdown afaik.

**Pull request merged**
